### ISSUE TITLE
Can't center image? It still stays in left.

### ISSUE THREAD

**Issue by anburocky3** [xeger/quill-image#20]
![image](https://user-images.githubusercontent.com/15264938/226779723-821cb7f9-dffd-4a5d-a985-f33fafb17bf4.png)

**Comment by xeger** [comment]
Image centering is accomplished with the `align` format. When you initialize your editor, make sure to specify align along with other formats (width, height, float, etc). See [the code sandbox](https://codesandbox.io/s/8fn0sp?file=/index.html:1697-1716) for example of proper initialisation with pure JS; you can extrapolate from there.

**Comment by anburocky3** [comment]
CSS was having like this.

```css
img, svg, video, canvas, audio, iframe, embed, object {
    display: block;
}
```

I replaced it with 

```css
img, svg, video, canvas, audio, iframe, embed, object {
    display: inline !important;
}
```

**Comment by anburocky3** [comment]
*Update:* I replaced it with below code, so it doesn't affect all img in the page.

```css
.ql-editor img, .ql-editor svg, .ql-editor video, .ql-editor canvas, .ql-editor audio, .ql-editor iframe, .ql-editor embed, .ql-editor object {
    display: inline !important;
}
```
